#!/usr/bin/env python3
"""Generate docs/history.html from `git log`.

Run at build time (GitHub Actions) so the change-history page is always
derived from git itself — the single source of truth. No manual upkeep.
"""

import html
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "history.html"

# Unit/record separators let us parse safely even when a commit body
# contains commas, newlines, etc.
FIELD = "\x1f"  # between fields of one commit
RECORD = "\x1e"  # between commits
FMT = FIELD.join(["%h", "%an", "%ad", "%s", "%b"]) + RECORD


def git_log():
    out = subprocess.run(
        ["git", "log", f"--pretty=format:{FMT}", "--date=short"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    commits = []
    for raw in out.split(RECORD):
        raw = raw.strip("\n")
        if not raw:
            continue
        sha, author, date, subject, body = raw.split(FIELD)
        commits.append(
            {
                "sha": sha,
                "author": author,
                "date": date,
                "subject": subject,
                "body": body.strip(),
            }
        )
    return commits


def render(commits):
    cards = []
    for c in commits:
        esc = {k: html.escape(v) for k, v in c.items()}
        body_html = f'<div class="body">{esc["body"]}</div>' if c["body"] else ""
        cards.append(
            f"""      <article class="commit">
        <div class="meta">
          <span class="sha">{esc['sha']}</span>
          <span>{esc['date']}</span>
          <span>{esc['author']}</span>
        </div>
        <div class="subject">{esc['subject']}</div>
        {body_html}
      </article>"""
        )

    count = len(commits)
    return f"""<!doctype html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>llm-app-lab — 변경 이력</title>
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div class="wrap">
      <header class="hero">
        <h1>변경 이력</h1>
        <p class="muted">
          커밋 {count}개 · 이 페이지는 push마다 <code>git log</code>로부터
          자동 생성됩니다. ← <a href="./index.html">개념 노트로 돌아가기</a>
        </p>
      </header>
{chr(10).join(cards)}
      <footer>
        <p>llm-app-lab · auto-generated by scripts/gen_history.py</p>
      </footer>
    </div>
  </body>
</html>
"""


def main():
    commits = git_log()
    OUT.write_text(render(commits), encoding="utf-8")
    print(f"wrote {OUT} ({len(commits)} commits)")


if __name__ == "__main__":
    main()
